# Solution 3.1

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [2]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.11353949, 0.44679324, 0.61521994, 0.1092468 , 0.03250815,
        0.21951307, 0.57173838, 0.66852547, 0.1049866 , 0.34648028],
       [0.41303181, 0.43211029, 0.80237242, 0.41864261, 0.9820886 ,
        0.70922514, 0.03476012, 0.4393986 , 0.50801944, 0.62517679],
       [0.03606801, 0.95277305, 0.29538603, 0.68810695, 0.72954502,
        0.25940247, 0.0036467 , 0.21562192, 0.48567681, 0.9323434 ],
       [0.54192224, 0.83455532, 0.89990691, 0.18269742, 0.15452794,
        0.98373522, 0.28428805, 0.89061376, 0.96278895, 0.05808479],
       [0.2172634 , 0.98529366, 0.40081746, 0.69663692, 0.73227035,
        0.6051795 , 0.8424847 , 0.68307044, 0.50980091, 0.44835563],
       [0.0469566 , 0.03960291, 0.65980532, 0.06143779, 0.86797069,
        0.71300925, 0.59184971, 0.58388372, 0.34245049, 0.57682867],
       [0.87459366, 0.08520522, 0.43782052, 0.1277214 , 0.7105141 ,
        0.98498984, 0.05507813, 0.05866033, 0.7602776 , 0.20099409],
       [0.28439671, 0.74757595, 0.1910034

In [3]:
#3.3: return only the odd rows of A
A[0:10:2,:] # start:stop:stepsize , all

array([[0.11353949, 0.44679324, 0.61521994, 0.1092468 , 0.03250815,
        0.21951307, 0.57173838, 0.66852547, 0.1049866 , 0.34648028],
       [0.03606801, 0.95277305, 0.29538603, 0.68810695, 0.72954502,
        0.25940247, 0.0036467 , 0.21562192, 0.48567681, 0.9323434 ],
       [0.2172634 , 0.98529366, 0.40081746, 0.69663692, 0.73227035,
        0.6051795 , 0.8424847 , 0.68307044, 0.50980091, 0.44835563],
       [0.87459366, 0.08520522, 0.43782052, 0.1277214 , 0.7105141 ,
        0.98498984, 0.05507813, 0.05866033, 0.7602776 , 0.20099409],
       [0.22999776, 0.99763712, 0.41065402, 0.96477836, 0.93011174,
        0.43999143, 0.24432215, 0.62842966, 0.57024065, 0.11480207]])

In [4]:
#3.4: perform a matrix multiplication of A with it's transposed
A.dot(A.T)

array([[1.55707047, 1.55050984, 1.28760882, 2.10811074, 2.0914358 ,
        1.58493079, 0.8801604 , 2.00839484, 1.61616679, 1.44391885],
       [1.55050984, 3.48708519, 2.77661681, 3.15909144, 3.14581725,
        2.76146754, 2.73876757, 2.10573728, 3.13107427, 2.38371743],
       [1.28760882, 2.77661681, 3.22099933, 2.28897342, 3.05154047,
        1.92695842, 1.67329298, 2.32939816, 3.05706452, 1.62675165],
       [2.10811074, 3.15909144, 2.28897342, 4.62933594, 3.50122031,
        2.55050678, 2.85272911, 2.64172839, 3.26443612, 3.03562673],
       [2.0914358 , 3.14581725, 3.05154047, 3.50122031, 4.20371213,
        2.75423556, 2.21899364, 3.42756927, 3.79428094, 2.40872996],
       [1.58493079, 2.76146754, 1.92695842, 2.55050678, 2.75423556,
        2.84585623, 2.10332323, 1.99430399, 2.27459466, 2.18265045],
       [0.8801604 , 2.73876757, 1.67329298, 2.85272911, 2.21899364,
        2.10332323, 3.08010414, 1.1762698 , 2.1903551 , 2.12969773],
       [2.00839484, 2.10573728, 2.3293981

In [5]:
#3.5: compute the matrix inverse of A
A_inv=np.linalg.inv(A)
np.isclose(A.dot(A_inv),np.identity(10))#test for identity AA^-1

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [6]:
#same in one line with where
np.where(A>0.5, A/2, A) # np.where(condition, Array to take value if condition is true, Array to take Value if condition is false )

array([[0.11353949, 0.44679324, 0.30760997, 0.1092468 , 0.03250815,
        0.21951307, 0.28586919, 0.33426273, 0.1049866 , 0.34648028],
       [0.41303181, 0.43211029, 0.40118621, 0.41864261, 0.4910443 ,
        0.35461257, 0.03476012, 0.4393986 , 0.25400972, 0.31258839],
       [0.03606801, 0.47638652, 0.29538603, 0.34405348, 0.36477251,
        0.25940247, 0.0036467 , 0.21562192, 0.48567681, 0.4661717 ],
       [0.27096112, 0.41727766, 0.44995346, 0.18269742, 0.15452794,
        0.49186761, 0.28428805, 0.44530688, 0.48139447, 0.05808479],
       [0.2172634 , 0.49264683, 0.40081746, 0.34831846, 0.36613518,
        0.30258975, 0.42124235, 0.34153522, 0.25490045, 0.44835563],
       [0.0469566 , 0.03960291, 0.32990266, 0.06143779, 0.43398535,
        0.35650463, 0.29592485, 0.29194186, 0.34245049, 0.28841433],
       [0.43729683, 0.08520522, 0.43782052, 0.1277214 , 0.35525705,
        0.49249492, 0.05507813, 0.05866033, 0.3801388 , 0.20099409],
       [0.28439671, 0.37378798, 0.1910034

In [7]:
# if we need only the values to change:
mask=A>0.5 #generate a mask with indix values
A[mask]/2 #manipulate Array at mask locations



array([0.30760997, 0.28586919, 0.33426273, 0.40118621, 0.4910443 ,
       0.35461257, 0.25400972, 0.31258839, 0.47638652, 0.34405348,
       0.36477251, 0.4661717 , 0.27096112, 0.41727766, 0.44995346,
       0.49186761, 0.44530688, 0.48139447, 0.49264683, 0.34831846,
       0.36613518, 0.30258975, 0.42124235, 0.34153522, 0.25490045,
       0.32990266, 0.43398535, 0.35650463, 0.29592485, 0.29194186,
       0.28841433, 0.43729683, 0.35525705, 0.49249492, 0.3801388 ,
       0.37378798, 0.37370864, 0.47666184, 0.45702482, 0.31237011,
       0.49881856, 0.48238918, 0.46505587, 0.31421483, 0.28512032,
       0.30374103, 0.3325519 , 0.35214084, 0.44183992])

In [8]:
#or even simpler
A[A>0.5]/2

array([0.30760997, 0.28586919, 0.33426273, 0.40118621, 0.4910443 ,
       0.35461257, 0.25400972, 0.31258839, 0.47638652, 0.34405348,
       0.36477251, 0.4661717 , 0.27096112, 0.41727766, 0.44995346,
       0.49186761, 0.44530688, 0.48139447, 0.49264683, 0.34831846,
       0.36613518, 0.30258975, 0.42124235, 0.34153522, 0.25490045,
       0.32990266, 0.43398535, 0.35650463, 0.29592485, 0.29194186,
       0.28841433, 0.43729683, 0.35525705, 0.49249492, 0.3801388 ,
       0.37378798, 0.37370864, 0.47666184, 0.45702482, 0.31237011,
       0.49881856, 0.48238918, 0.46505587, 0.31421483, 0.28512032,
       0.30374103, 0.3325519 , 0.35214084, 0.44183992])